### ISSUE TITLE
Wireframe the site

### ISSUE THREAD

**Issue by MikeGalli** [suwebdev/ancient-fog#3]
Related user story: https://github.com/suwebdev/ancient-fog/wiki/User-Story%3A-View-Public-Website
Estimated size = XXL
What is the priority that has been assigned? This is issue has been assigned 1st priority
This issue involves having an actual website. Before this can happen,, a wireframe needs to be created and approved. We have decided to create the simplest version of the site possible. The first roll-out will be a one page site that shows poem and drink parings and allows the visitor to rate the parings. Later, other features will be added:
    • The site will "listen" to ratings and modify poem and drink parings based on the ratings.
    • Poets will be allowed to upload their own poems and suggest drink parings.
    • Other data will be collected based on other user stories.
Why should this be in the Sprint this time? Why not wait until the next Sprint? This issue represents the framework from which we will build out all subsequent features and functionality.

**Comment by branchaw** [comment]
This issue refers primarily to User Story Navigation, then to other stories listed.

**Comment by lukegreen** [comment]
Closing this so that we can submit our assignments.
